# Generated by Django 2.2 on 2019-05-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Room'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='season',
            field=models.CharField(choices=[('SP', 'SPRING'), ('F', 'FALL')], max_length=1),
        ),
    ]
