# Generated by Django 2.2 on 2019-06-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('student', 'course', 'year', 'season')},
        ),
    ]
