# Generated by Django 2.2 on 2019-05-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='gradeReceived',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
