# Generated by Django 2.2 on 2019-05-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190507_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Room'),
        ),
    ]
