# Generated by Django 2.2 on 2019-05-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190516_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isInCatalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='second_email',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
