# Generated by Django 2.2 on 2019-05-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190525_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_email',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
