# Generated by Django 2.2 on 2019-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190430_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisor',
            unique_together={('faculty', 'student')},
        ),
    ]
