# Generated by Django 2.2 on 2019-05-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190430_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='isTaken',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='room',
        ),
    ]
